### ISSUE TITLE
Is it not possible to properly switch fb account

### ISSUE THREAD

**Issue by StanDem** [TomGrill/gdx-facebook#11]
Hello,

It seems that in the newest version there's no way to properly log-out and log-in again under different fb account. 
Yes, we can always do a graph request to revoke permissions. But this will deauthorize the app on a specific platform. 
E.g if you have logged in on several android devices. Then you do that kind of log-out on a single device. This will make you log-out an all devices! That's not a normal behavior that we usually see in the games.

I've tested a clean facebook android SDK, it allows you to log out on a single device and log-in again under a different account.

If I'm correct, in the older gdx-facebook version, the local access token cache was cleared every time after log out. This was enough to be able to re-login again.

Is it possible to do something about that?
Thanks!

ps. As a workaround I manually clear the .fbsession prefs file on log-out.

**Comment by TomGrill** [comment]
If I remember right the iOS SDK does not allow to switch accounts at all. So I wanted it to make be the same on all platforms. I would like to be able to switch accounts too. I will think about at good solution for this.

**Comment by TomGrill** [comment]
I implemented what I think is the best approach and fits your requirements.

New method:
`public void signOut(boolean keepSessionData);`

Explanation:
Signs the user out. When keepSessionData is false then all session data for the current user will be deleted and the user needs to login and auth the app again. When keepSessionData is true
	 the session data is stored and reused with the next login.
	 NOTE: When the user has native Facebook App installed on his device keepSessionData = false does not always work.
	  In this cases you may want to give the user a hint that he needs to logout from Facebook App in order to be able to switch accounts.

Published in current SNAPTSHOT 1.1.1

**Comment by StanDem** [comment]
Works perfect. Thank you for the quick fix!
