### ISSUE TITLE
Token expiration time is incorrect on Desktop

### ISSUE THREAD

**Issue by StanDem** [TomGrill/gdx-facebook#12]
on Desktop:
token.getExpiresAt(): 1453044939
Converted: 1970-01-17T19:37:24.939Z (incorrect)

iOS, Android:
token.getExpiresAt(): 1453044940637
Converted: 2016-01-17T15:35:40.637Z (correct)

I have to manually multiply the value by 1000 to get the correct date. It looks like you get seconds instead on milliseconds on Desktop via getExpiresAt() method.
iOS, Android - OK.

**Comment by TomGrill** [comment]
Thanks, fixed in current snapshot build 1.1.1.
