### ISSUE TITLE
Not able to send game request

### ISSUE THREAD

**Issue by aryan9234** [TomGrill/gdx-facebook#14]
I have no idea how to send game request from app but i am trying as you specify on wiki but user didn't get any request from my app.

**Comment by TomGrill** [comment]
Can you give a more precise error description. Any log output?

It is possible that your facebook app requires a review by facebook before this feature is enabled.

Did you test with test users or real users?

**Comment by aryan9234** [comment]
There is no error, problem is user didn't get any request. Is there any special review by facebook. Currently with my app id i can login and able to post on timeline.

**Comment by aryan9234** [comment]
thanks for quick response. ya you are right. App haven't review by facebook but It require Privacy Policy URL for review but i haven't as i am indie developer. please suggest what should i do.

**Comment by TomGrill** [comment]
Probably the best way to go is get a cheap domain from a cheap hoster. Costs around $10 per year.

**Comment by Yayo-Arellano** [comment]
You can do a very simple privacy policy. like mine http://privacy.tiarsoft.com/
