### ISSUE TITLE
It doesn't compile with the GWT backend

### ISSUE THREAD

**Issue by lozan** [TomGrill/gdx-facebook#15]
I tried this on a project which I am building for all platforms, and all of them except the GWT are compiling just fine. I expected that it won't work for GWT, but I thought that it would at least compile. Are there any plans to make it work with GWT or at least provide placeholder classes so it would compile?
Otherwise, I'd have to make a wrapper for gdx-facebook, which seems kind of weird, as it is after all a library that's supposed to work with LibGDX and a pretty good one imho.

**Comment by TomGrill** [comment]
Can you post the compiler error please.

**Comment by lozan** [comment]
I used OAuth and graph api for facebook for the time being, so I don't have the compiler errors. I should have included them in my original post, but the thing is that for any type from gdx-facebook it said that the class doesn't exist. You may just try to compile a sample app which does sign-in and you should get the errors. However, if there's a gwt.xml file there which includes the core and html it should compile.

**Comment by TomGrill** [comment]
no longer relevant I think. Please create new issue if not.
