### ISSUE TITLE
Question: Default sharing interfaces (Like, Share), posting content

### ISSUE THREAD

**Issue by SuperBadger** [TomGrill/gdx-facebook#16]
Hi there,

Is there any way at the moment to post any kind of content to a user's page without going through the Facebook review? If not, would it be possible to implement calling of the default sharing interfaces as described here? [https://developers.facebook.com/docs/sharing/android](url)

Note: My use case is the following: On Android, the user logs in by default with read privileges, when user starts the "share on Facebook" process at some point while using the app, login with write privileges will initiate. If successful, either a standardized post is written on their page (such as a "Like" post, or any other pre-authorized by Facebook), or the Facebook app takes over and shows a Share dialog (as described in the link above), which the user can then confirm or cancel.

When attempted via gdx-facebook, it runs into several issues. Firstly, logging in with write privileges when the user is logged in (as recommended by Facebook) does not work, as gdx-facebook finds a valid access token with read privileges, uses it and wrongly returns success on the callback (for the login with write privileges), which results in the following error when attempting to post:

(#200) The user hasn't authorized the application to perform this action","type":"OAuthException","code":200

If there's another way to achieve the same effect or I'm misusing the API, feel free to correct me.

Thanks.

**Comment by TomGrill** [comment]
I will look into this but it will take some time. Very busy at the moment.

**Comment by TomGrill** [comment]
Can you share your code including login process for read/write privileges and for your share implementation?

**Comment by TomGrill** [comment]
I assume this is done. Reopen if not.
