### ISSUE TITLE
getting a ReflectionException while testing with android 4.0.4 device

### ISSUE THREAD

**Issue by youngsuksong** [TomGrill/gdx-facebook#18]
hello Tom

I got the following exception while testing with my android 4.0.4 ice cream sandwich mobile phone.
When I test on Android 4.2 JellyBean and 6.0 marshmallow, I did not get any exception and it worked perfectly. Do you have any idea why it is crashing on Android 4.0.4?

E/gdx-facebook (1.1.1): Error installing gdx-facebook (1.1.1) for Android
E/gdx-facebook (1.1.1): Did you add >> compile "de.tomgrill.gdxfacebook:gdx-facebook-core:1.1.1" << to your gradle dependencies? View https://github.com/TomGrill/gdx-facebook/wiki for more information.
W/System.err: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in constructor for class: com.myproject.gdxfacebook.android.AndroidGDXFacebook
W/System.err:     at com.badlogic.gdx.utils.reflect.Constructor.newInstance(Constructor.java:62)
W/System.err:     at com.myproject.gdxfacebook.GDXFacebookSystem.tryToLoadAndroidGDXFacebook(GDXFacebookSystem.java:88)
W/System.err:     at com.myproject.gdxfacebook.GDXFacebookSystem.installSystem(GDXFacebookSystem.java:35)
W/System.err:     at com.myproject.gdxfacebook.GDXFacebookSystem.install(GDXFacebookSystem.java:26)
W/System.err:     at com.myproject.FacebookManager.<init>(FacebookManager.java:72)
W/System.err:     at com.myproject.MyFirstGame.createFacebookManager(MyFirstGame.java:294)
W/System.err:     at com.myproject.MyFirstGame.create(MyFirstGame.java:212)
W/System.err:     at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:254)
W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1456)
W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1217)
W/System.err: Caused by: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
W/System.err:     at com.badlogic.gdx.utils.reflect.Constructor.newInstance(Constructor.java:53)
W/System.err: 	... 9 more
W/System.err: Caused by: java.lang.ExceptionInInitializerError
W/System.err:     at com.facebook.FacebookSdk.getExecutor(FacebookSdk.java:378)
W/System.err:     at com.facebook.internal.Utility.loadAppSettingsAsync(Utility.java:778)
W/System.err:     at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:211)
W/System.err:     at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:174)
W/System.err:     at com.myproject.gdxfacebook.android.AndroidGDXFacebook.<init>(AndroidGDXFacebook.java:38)
W/System.err: 	... 12 more
W/System.err: Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
W/System.err:     at android.os.Handler.<init>(Handler.java:121)
W/System.err:     at android.os.AsyncTask$InternalHandler.<init>(AsyncTask.java:607)
W/System.err:     at android.os.AsyncTask$InternalHandler.<init>(AsyncTask.java:607)
W/System.err:     at android.os.AsyncTask.<clinit>(AsyncTask.java:190)
W/System.err: 	... 17 more

**Comment by TomGrill** [comment]
The package name seams odd: com.myproject.gdxfacebook.android.AndroidGDXFacebook

Usually the package name should be de.tomgrill.gdxfacebook.android..AndroidGDXFacebook

Did you use the source code and renamed package names somehow?

The classnames are hardcoded in GDXFacebookVars class and should not be changed at all.

**Comment by youngsuksong** [comment]
yes, I changed the package name. I studied your code and I added few more methods and I changed the package name.

I also changed the hardcoded classnames in GDXFacebookVars class as well, and GDXFacebook worked perfectly in Android API 17+

I will change the package name back to the original name but I don't think that is the problem since I already tested it multiple times with other devices and verified it is working. I did not get the ReflectionException with the devices which is running on Android API 17 or above.

The problem occurred when I was testing with IceCream Sandwich Android API 15 device. The ReflectionException occurred in the below line in tryToLoadAndroidGDXFacebook()  method.

Object facebookObj = ClassReflection.getConstructor(facebookClazz, activityClazz, GDXFacebookConfig.class).newInstance(activity, config);

so you did not get any exception like this when you were testing with IceCream Sandwich device?

**Comment by TomGrill** [comment]
Unfortunately I do not have access to an IceCream Sandwich device for testing. I think we need somebody else to confirm/negate the problem.

**Comment by youngsuksong** [comment]
I will post this problem in the Libgdx community forum. Thank you for the quick reply.

**Comment by TomGrill** [comment]
closed, no help/no solution so far in this case. Sorry!
