### ISSUE TITLE
Please add token expiration time to the GDXFacebookLoginResult

### ISSUE THREAD

**Issue by StanDem** [TomGrill/gdx-facebook#2]
Hello,
I'm trying to implement facebook and parse linking via parse REST api.
It requires to provide facebook access token expiration time.
Could you please add this value to your GDXFacebookLoginResult class?

**Comment by TomGrill** [comment]
I will look into this this weekend.

**Comment by StanDem** [comment]
Actually, login to Parse requires:
1) facebook user id
2) access token
3) token expirtaion time

So also it would be great to have an ability to get a facebook user id from the GDXFacebookLoginResult  right after the fb login, without making a separate Graph request. 
At least this is how it made in some official Parse SDK's.

ps. Thank you for your lib, it's really helping!

**Comment by TomGrill** [comment]
I have added your requested feature. Please try 0.5.0-SNAPSHOT.

The GDXFacebookLoginResult now contains a GDXFacebookAccessToken which holds all the required information.

Please test and give me feedback.

**Comment by StanDem** [comment]
Thanks! Works perfectly as it should!
Just one thing, I forgot about user name field, I hope it would not be so hard to get user name field from the same request and put it to your result class? If not, it's just fine already =)

**Comment by StanDem** [comment]
It looks like there is a major issue regearding debug_token.
If you try to login to fb not via your developer account, you will get this error

READ REQUEST: Error login: (#100) You must provide an app access token or a user access token that is an owner or developer of the app

So this happens when a logged fb user, who is no an app developer, tries to do a "debug_token" graph api request.
https://developers.facebook.com/docs/graph-api/reference/v2.4/debug_token

"An app access token or an app developer's user access token for the app associated with the input_token is required to access this endpoint."

Actually do we really need this debug_token? I thought expiration time might be obtained without it.

At this point it appears that only a developer of the app can login to facebook until this issue is resolved... =)

**Comment by TomGrill** [comment]
well than this must be removed and replaced with individual querys to gain userinformation.

**Comment by StanDem** [comment]
I would agree, but as I said before there's no issue at all on iOS and Android.
If it's not desktop part of the code specific, then maybe this is something related to app settings on facebook dev console idk.

**Comment by TomGrill** [comment]
thing is the SDKs for Android and iOS do a lot of token management stuff in the background. Which means the easy access is restricted. So every additional information can only gained by an additional query. Now the questions is, is this the job of the developer or of the extension. Its tricky :)
