### ISSUE TITLE
Trying to log in crashes the Android app

### ISSUE THREAD

**Issue by gronholm** [TomGrill/gdx-facebook#20]
My Android app crashes after trying to log in. Yesterday it was working fine. Today morning I noticed that I had lost my keystore file, so I had to change my package name. After this, logging in doesn't work anymore. Any help?

Log gives this output:
> 03-26 14:41:17.055 11888-11907/? D/gdx-facebook (1.1.1): Skip installing gdx-facebook (1.1.1) for Desktop. Not running Desktop. 
> 03-26 14:41:17.060 11888-11907/? D/gdx-facebook (1.1.1): Skip installing gdx-facebook (1.1.1) for WebGL. Not running WebGL. 
> 03-26 14:41:17.060 11888-11907/? D/gdx-facebook (1.1.1): Skip installing gdx-facebook (1.1.1) for iOS. Not running iOS. 
> 03-26 14:41:17.060 11888-11907/? D/gdx-facebook (1.1.1): gdx-facebook (1.1.1) for Android installed successfully.
> 03-26 14:41:17.060 11888-11907/? D/gdx-facebook (1.1.1): Could not load existing accessToken
> 03-26 14:41:17.060 11888-11907/? D/gdx-facebook (1.1.1): Starting GUI sign in.
> 03-26 14:41:17.075 2418-3066/? E/Parcel: Class not found when unmarshalling: com.facebook.login.LoginClient$Request

and a bit later:

> 03-26 14:41:21.290 11953-11953/? E/AndroidRuntime: FATAL EXCEPTION: main
>                                                    Process: com.albertgronholm.kamalanew, PID: 11953
>                                                    java.lang.RuntimeException: Unable to resume activity {com.albertgronholm.kamalanew/com.facebook.FacebookActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
>

**Comment by TomGrill** [comment]
When changing the package name you probably have to update your Facebook App settings related to Android. Google Play Package Name, Class Name and Key Hashes.

**Comment by gronholm** [comment]
I tried that and also made a completely new Facebook App and got the same error. I also tried making a new empty libgdx project and copypasting my code to it - same results. So it must be something really messed up with my code. Weird because I tried reverting my code to a version that did work before, and it didn't work. Any guesses where that error could be coming from?

**Comment by gronholm** [comment]
Yeah. It wasn't a gdx-facebook issue, but something with the screens. Sorry for bothering!
