### ISSUE TITLE
[HELP] How can I do a share?

### ISSUE THREAD

**Issue by xirtam-ch** [TomGrill/gdx-facebook#23]
Here is my code.
Login:
`public static void login(final GDXFacebook gdxFacebook, final XFBListener listener) {
        Array<String> permissions = new Array<String>();
        gdxFacebook.signIn(SignInMode.READ, permissions, new GDXFacebookCallback<SignInResult>() {
            @Override
            public void onSuccess(SignInResult result) {
                post(gdxFacebook);
                listener.onSuccess();
            }

            @Override
            public void onError(GDXFacebookError error) {
                // Error handling
               
                listener.onFailed();
            }

            @Override
            public void onCancel() {
                // When the user cancels the login process
                listener.onFailed();
                
            }

            @Override
            public void onFail(Throwable t) {
                // When the login fails
                
                listener.onFailed();
            }
        });
    }`

`public static void post(final GDXFacebook gdxFacebook) {
        GDXFacebookGraphRequest request = new GDXFacebookGraphRequest().setNode("xirtamgame/feed").useCurrentAccessToken();
        request.setMethod(Net.HttpMethods.POST);
        request.putField("link", "https://www.google.com");
        request.putField("message", "message");

        gdxFacebook.newGraphRequest(request, new GDXFacebookCallback<JsonResult>() {

            @Override
            public void onSuccess(JsonResult result) {
                // Success
            }

            @Override
            public void onError(GDXFacebookError error) {
                // Error
            }

            @Override
            public void onFail(Throwable t) {
                // Fail
            }

            @Override
            public void onCancel() {
                // Cancel
            }

        });
    }`

I got
"error":{"message":"(#200) The user hasn't authorized the application to perform this action","type":"OAuthException","code":200

I want only share a link,help plz.

**Comment by xirtam-ch** [comment]
I found your example,thx.

**Comment by MohammadAbbasKhan** [comment]
can u provide a link for example
