### ISSUE TITLE
GWT/HTML5 Implementation

### ISSUE THREAD

**Issue by CypherEA** [TomGrill/gdx-facebook#24]
HI,

I got this working on Desktop and Android, but I'd love to also get it to work on GWT.
My game is cross platform, and allows direct cross platform play. And I've integrated Facebook login/register along side direct login/register to my site.

How do I make it work, the Facebook login, with HTML5?

**Comment by TomGrill** [comment]
GWT/HTML5 backend is currently not (yet) supported.

**Comment by CypherEA** [comment]
Any ETA?

**Comment by TomGrill** [comment]
No ETA sorry.

**Comment by TomGrill** [comment]
experimental GWT support with 1.2.0

**Comment by CypherEA** [comment]
Excellent. Thanks!

Changed the build.gradle to 1.2.0:

**Could not find de.tomgrill.gdxfacebook:gdx-facebook-android:1.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/de/tomgrill/gdxfacebook/gdx-facebook-android/1.2.0/gdx-facebook-android-1.2.0.pom
         https://repo1.maven.org/maven2/de/tomgrill/gdxfacebook/gdx-facebook-android/1.2.0/gdx-facebook-android-1.2.0.jar
         https://oss.sonatype.org/content/repositories/snapshots/de/tomgrill/gdxfacebook/gdx-facebook-android/1.2.0/gdx-facebook-android-1.2.0.pom
         https://oss.sonatype.org/content/repositories/snapshots/de/tomgrill/gdxfacebook/gdx-facebook-android/1.2.0/gdx-facebook-android-1.2.0.jar
         https://oss.sonatype.org/content/repositories/releases/de/tomgrill/gdxfacebook/gdx-facebook-android/1.2.0/gdx-facebook-android-1.2.0.pom
         https://oss.sonatype.org/content/repositories/releases/de/tomgrill/gdxfacebook/gdx-facebook-android/1.2.0/gdx-facebook-android-1.2.0.jar**

**Comment by TomGrill** [comment]
My bad, forgot to press the not so shiny release button. Now it should work.

**Comment by CypherEA** [comment]
Yeap. Works now!
Thanks.

Is the Wiki updated with what to do to get it to work in the HTML project?

**Comment by TomGrill** [comment]
Yep :)

**Comment by CypherEA** [comment]
Okay, so added the <source path... things from your wiki (btw, the gwt.xml in your sample app is not updated with these). Now getting this:

Compiling module com.caracri.game.GdxDefinition
   Validating units:
      [ERROR] Errors in 'file:/C:/Users/Cypher/Documents/NetBeansProjects/caracri/core/src/common/CaracriFacebookConfig.java'
         [ERROR] Line 15: No source code is available for type de.tomgrill.gdxfacebook.core.GDXFacebookConfig; did you forget to inherit a required module?
      [ERROR] Errors in 'file:/C:/Users/Cypher/Documents/NetBeansProjects/caracri/core/src/common/CaracriFacebookObject.java'
         [ERROR] Line 35: No source code is available for type de.tomgrill.gdxfacebook.core.GDXFacebookSystem; did you forget to inherit a required module?
         [ERROR] Line 45: No source code is available for type de.tomgrill.gdxfacebook.core.SignInMode; did you forget to inherit a required module?
         [ERROR] Line 45: No source code is available for type de.tomgrill.gdxfacebook.core.GDXFacebookCallback<T>; did you forget to inherit a required module?
         [ERROR] Line 45: No source code is available for type de.tomgrill.gdxfacebook.core.SignInResult; did you forget to inherit a required module?
         [ERROR] Line 56: No source code is available for type de.tomgrill.gdxfacebook.core.GDXFacebookError; did you forget to inherit a required module?
         [ERROR] Line 82: No source code is available for type de.tomgrill.gdxfacebook.core.GDXFacebook; did you forget to inherit a required module?
         [ERROR] Line 93: No source code is available for type de.tomgrill.gdxfacebook.core.GDXFacebookGraphRequest; did you forget to inherit a required module?
         [ERROR] Line 95: No source code is available for type de.tomgrill.gdxfacebook.core.JsonResult; did you forget to inherit a required module?
   [ERROR] Aborting compile due to errors in some input files

**Comment by TomGrill** [comment]
The gwt.xml in sample app has the 2 lines:
https://github.com/TomGrill/gdx-facebook-app/blob/master/core/src/GdxFacebookSampleApp.gwt.xml

I am not good with this GWT stuff. Cannot help you atm.

**Comment by TomGrill** [comment]
Since the way to implement gdx-facebook as GWT module changed like 5 minutes ago, I recommend to start all over.

Wiki and sample application are updated accordingly.

**Comment by CypherEA** [comment]
Dude, you rock.

err... did you press the Release button? ;D

**Comment by TomGrill** [comment]
like a bous
