### ISSUE TITLE
libgdx 1.93 changes - verify/fix that extension works with intel multi-os engine for ios

### ISSUE THREAD

**Issue by TomGrill** [TomGrill/gdx-facebook#26]
libgdx 1.93 changes - verify/fix that extension works with intel multi-os engine for ios

**Comment by TomGrill** [comment]
Update: July 10th 2016
there is branch ios-moe, but:
We need facebook SDK bindings first. Anybody knows how to do?

**Comment by ruffiely** [comment]
How about that I see an ios-moe package and Moe said they included the binding with 1.3 but I can't  compile

**Comment by TomGrill** [comment]
1.4.0 has ios-moe support now.
