### ISSUE TITLE
Decision: Keep login/logout to client

### ISSUE THREAD

**Issue by TomGrill** [TomGrill/gdx-facebook#28]
Instead of providing a kinda user friendly login mechanism with this library let the implementer of this lib do this? Give the tools, let user handle how he wants, is probably the better approach? Any opinions?

Same is with token storage. This is a security risk in my opinion and should also be managed by the implementer. Any opinions?

**Comment by ttencate** [comment]
I agree. I have a use case, highscores, where I need to first send a read request to fetch the current score, compare, and then possible send a publish request to update the score. I'm currently logging in again before each of these, but the sequencing is tricky.

It would be better if I just got a GdxFacebookToken that I could set on the request, so I could manage these myself. Looking at the code, I see that I can do this by manually adding a request parameter, which I'll do for now -- but first class support, and the ability to disable gdx-facebook's own token storage, would be nice.

**Comment by TomGrill** [comment]
With next major release probably 1.4 this will be changed.
