### ISSUE TITLE
GWT module

### ISSUE THREAD

**Issue by czyzby** [TomGrill/gdx-facebook#30]
You shouldn't force your users to include your sources in their GWT definition files like this:

```
<source path="de/tomgrill/gdxfacebook/core" />
<source path="de/tomgrill/gdxfacebook/html" />
```
Instead, you can create a GWT module that your users can simply inherit, similarly to how LibGDX libraries themselves are used:
```
<inherits name="com.badlogic.gdx.backends.gdx_backends_gwt" />
```

This way you have complete control over how your sources are included in GWT projects and you can exclude some problematic classes in the future without breaking existing applications, for example.

**Comment by TomGrill** [comment]
thanks will be fixed soon.

**Comment by TomGrill** [comment]
Ok, tried 1.5 hours to get this done. This GWT stuff I just don't get.

Need help/advice how to do this in detail.

**Comment by czyzby** [comment]
Add something like this in `de.tomgrill.gdxfacebook.core` package (name it `GdxFacebookCore.gwt.xml`):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit trunk//EN" "http://google-web-toolkit.googlecode.com/svn/trunk/distro-source/core/src/gwt-module.dtd">
<module>
	<source path="" />
</module>
```

Then add this to `de.tomgrill.gdxfacebook.html` package:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit trunk//EN" "http://google-web-toolkit.googlecode.com/svn/trunk/distro-source/core/src/gwt-module.dtd">
<module>
	<source path="" />
	<inherits name="de.tomgrill.gdxfacebook.core.GdxFacebookCore" />
</module>
```

Users of your library will be able to use your module by inheriting `de.tomgrill.gdxfacebook.html.WhateverYouNameTheSecondFile`.

**Comment by TomGrill** [comment]
Thank you very much. Works great.
