### ISSUE TITLE
Building GWT throws Errors in usages of some methods 

### ISSUE THREAD

**Issue by CypherEA** [TomGrill/gdx-facebook#31]
In: de/tomgrill/gdxfacebook/core/GDXFacebookMultiPartRequest.java

[ERROR] Line 51: No source code is available for type java.io.FileInputStream; did you forget to inherit a required module?
[ERROR] Line 117: The method file() is undefined for the type FileHandle
[ERROR] Line 139: The method file() is undefined for the type FileHandle

Java.io is not supported by GWT, so maybe use @GwtIncompatible annotation for the loadFile method.

The second and third lines are using com.badlogic.gdx.files package - so need to get those to GWT.

In: de/tomgrill/gdxfacebook/core/utils/Utils.java

[ERROR] Line 46: No source code is available for type java.net.URL; did you forget to inherit a required module?
[ERROR] Line 72: No source code is available for type java.net.MalformedURLException; did you forget to inherit a required module?
[ERROR] Line 81: No source code is available for type java.net.URLDecoder; did you forget to inherit a required module?

URLDecoder is weird, cause I'm using URLEncoder in another part of my game, and it compiles in GWT perfectly,

**Comment by TomGrill** [comment]
fixed with 1.2.2
