### ISSUE TITLE
Cannot login using LibGDX Desktop platform

### ISSUE THREAD

**Issue by Haapavuo** [TomGrill/gdx-facebook#33]
Facebook Sign in fails with the following error message: **Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.**

Any fix for this?

**Comment by TomGrill** [comment]
Go to your facebook app settings in the facebook developer section and add the URL.

**Comment by Haapavuo** [comment]
My app does not have Client OAuth Settings. I have done everything else accordingly.

**Comment by Haapavuo** [comment]
Update: For me the Client OAuth Settings are not on the same page. I must select under PRODUCTS: Facebook-login -> Client OAuth Settings. Your wiki tells me to scroll down which did not help in my case. Maybe the Facebook developer page has been updated?

**Comment by TomGrill** [comment]
Well things change from time to time. In spirit of open source thinking feel free to edit outdated Wiki parts :)
