### ISSUE TITLE
Graph API Nested GET Requests not working

### ISSUE THREAD

**Issue by Haapavuo** [TomGrill/gdx-facebook#34]
https://developers.facebook.com/docs/graph-api/using-graph-api/#fieldexpansion

For example

`request.setNode("me?fields=link,first_name,last_name,email,gender,locale,picture");`

Always results in an error ("An active access token must be used to query information about the current user."). Permissions are set correctly when signing in.

Any fix for this?

**Comment by TomGrill** [comment]
Try:
```
request.setNode("me");
request.putField("fields", "link,first_name,last_name,email,gender,locale,picture");
```

**Comment by Haapavuo** [comment]
Thank you, it worked.
