### ISSUE TITLE
Cannot install on iOS since 1.2.1

### ISSUE THREAD

**Issue by MrCharli3** [TomGrill/gdx-facebook#35]
Hi,

Since I updated to 1.2.1 gdx-facebook cannot install on any of my iOS devices. It worked fine on my older version. Not sure if this is a known issue. I get the standard Error, asking if I've added gdx-facebook to my build.gradle file, which I have :)

**Comment by TomGrill** [comment]
Are you using ios-robovm (should work) or ios-moe (not supported yet)?
Did some changes, nothing related to ios but use latest version 1.2.2 please.

**Comment by MrCharli3** [comment]
That could be the issue, have not seen that. Also realized I was one version behind after I posted. I will test again tomorrow and let you know if the problem persists, thanks!

**Comment by TomGrill** [comment]
I assume this is done. Reopen if not.
