### ISSUE TITLE
roboVMGradleVersion = "2.0.0-SNAPSHOT" out of date

### ISSUE THREAD

**Issue by max-tu** [TomGrill/gdx-facebook#37]
please update new version of roboVMGradleVersion to 2.1.0 or 2.2.0
Could not find com.mobidevelop.robovm:robovm-gradle-plugin:2.2.0-SNAPSHOT
![out](https://cloud.githubusercontent.com/assets/9456746/18076841/5766b1ac-6eab-11e6-8dd7-053e8b6c9596.png)+

**Comment by TomGrill** [comment]
fixed with 1.3.0, coming in few hours
