### ISSUE TITLE
isSignedIn() does not check session file

### ISSUE THREAD

**Issue by ghandhikus** [TomGrill/gdx-facebook#38]
There is no way to silently check if user has already logged in before. SignIn loads the session and forces the user to log in. I can't forcefully check only facebook if i have a few logging in methods. Perhaps there is hidden loadSession() function somewhere?

**Comment by TomGrill** [comment]
FB SDK has removed the silent login a few versions ago. So right now the login is either silent because the SDK already has credentials it can use or the login windows will appear. No way to control this behavior.

**Comment by ghandhikus** [comment]
So any clue on how can i check if session file is still correct without logging in?

**Comment by TomGrill** [comment]
You can verify session tokens against the graph API. https://graph.facebook.com/app/?access_token=[user_access_token] But there are some limitations. Read the doc!

**Comment by ghandhikus** [comment]
But why does the lib not provide that? Why can't it just log in once, and then have checkSessionFileToken() function. There is already a file with session token for "silent login". So why do users need to write their own checking on top of it? Even if I'd code it myself, then I can't get token from it until it is going to load the session file, which it does only if I force the signIn().

So what I would need to do is to write it a hacky way on top of this lib, by storing session token after user once has signed in, because there is no function to get the key from the file, nor to check it out of the box.

I know that I can just write my own stuff, but why is the lib not doing this for me?

**Comment by TomGrill** [comment]
If you think there is feature missing, best thing would be to add it and make PR. 

But keep in mind that token storage will be changed in sometime in future: https://github.com/TomGrill/gdx-facebook/issues/28
