### ISSUE TITLE
Is this possible to use GDX-Facebook without LibGDX?

### ISSUE THREAD

**Issue by spectre329** [TomGrill/gdx-facebook#39]
Hi. I have integrated GDX Facebook with my game client. Now I need to authenticate the user, so I send the token to the server and it should 'GET' the url with token as you wrote on WIKI and get the results in json. As I can see in code, you've implemented json parsers, errors and it would be useful if I just use your system on the server (which is only a java application). Is there a version which doesn't require GDX?

Thanks! And I'm sorry I wrote here, I know that there are only issues.

**Comment by TomGrill** [comment]
Probably not. However there is a implementation for each platform, so you can probably pick the code for your platform and adapt it to your needs.
