### ISSUE TITLE
Please implement Game Requests(enhancement)

### ISSUE THREAD

**Issue by StanDem** [TomGrill/gdx-facebook#4]
This is usually used to invite fb friends to your game and always been important part of the app's social integration. I really need this functionality for my game.
As far as I know there's not much code required from platform-specific fb SDK's to call this request dialog.
Please refer to this article to see what I'm talking about:
https://developers.facebook.com/docs/games/requests/v2.4

**Comment by TomGrill** [comment]
Sorry StanDem, I don't have the time to implement and test new features (which I do not require at the moment) at the moment. Feel free to add it by your self and make a pull request.

**Comment by TomGrill** [comment]
Update: I consider adding this to one of my apps. But I cannot promise anything.

**Comment by StanDem** [comment]
That's a great news.
Btw, the implementation is super easy.  I temporary made it via "ugly" interface resolving for each platform.
But I still think It's right way to write things once in the core project and let the libs do the rest for platforms. =)

Here is the code, which I've tested and it works:
for iOS:
```
public void Invite() {
            final FBSDKGameRequestContent gameRequestContent = new FBSDKGameRequestContent();
            gameRequestContent.setMessage("Play XXX on your device!");

          FBSDKGameRequestDialog.show(gameRequestContent, new FBSDKGameRequestDialogDelegateAdapter() {
                @Override
                public void didComplete(FBSDKGameRequestDialog gameRequestDialog, NSDictionary<?, ?> results) {
                }

                @Override
                public void didFail(FBSDKGameRequestDialog gameRequestDialog, NSError error) {
                }

                @Override
                public void didCancel(FBSDKGameRequestDialog gameRequestDialog) {
                }
            });
    }
```

for Android
```
    public void Invite() {
        GameRequestContent content = new GameRequestContent.Builder()
                .setMessage("Play XXX on your device!")
                .build();
        GameRequestDialog requestDialog = new GameRequestDialog(context);
        requestDialog.registerCallback(((AndroidLauncher) context).callbackManager, new FacebookCallback<GameRequestDialog.Result>() {
            public void onSuccess(GameRequestDialog.Result result) {
             }

            public void onCancel() {
            }

            public void onError(FacebookException error) {
            }
        });
        requestDialog.show(content);
    }  

Also main activity should contain public CallbackManager callbackManager = CallbackManager.Factory.create();
and 
   callbackManager.onActivityResult(requestCode, resultCode, data);  in onActivityResult.

```

**Comment by TomGrill** [comment]
FYI: Planing to add this feature after rewriting hole extension. Got to messy.

**Comment by TomGrill** [comment]
0.6.0 has a basic support for Game Requests.
