### ISSUE TITLE
Error:(3, 5) No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').

### ISSUE THREAD

**Issue by jr69** [TomGrill/gdx-facebook#41]
I get this error trying to do the Android installation.

I have searched up on this bug, but the answers only relate to Android and not LibGDX:

http://stackoverflow.com/questions/35963144/no-resource-found-that-matches-the-given-name-at-cardbackgroundcolor-with-val

If you visit those links, you will see that the answer suggests having an upgraded version of the facebook sdk, but there is no such option since the instructions only tell you to put this gdx-facebook as a dependency, and not the facebook sdk

**Comment by TomGrill** [comment]
Next release will contain the latest Android Facebook SDK
