### ISSUE TITLE
GameRequestDialog on Android requires authorization again

### ISSUE THREAD

**Issue by trokamp** [TomGrill/gdx-facebook#42]
Hi

In my app, when I login to facebook, the access-token is saved and everything is fine. Silent-login works when I try to login again.
If I am in an active session where I recently entered my login and password, then when I try sending a game request with the game request dialog, it will show the persons available for invitation.
If on the other hand I have been logged in silently and try to send the same game request with the dialog, I am asked to re-enter my login and password, which is very strange, as I have already silently logged in.

Any explanation of this or just a "feature" (bug)?

Let me know if you need anything else from me.

Best regards,
Thomas

**Comment by trokamp** [comment]
Here is a screencast showing the issue - the login type is silent

https://youtu.be/m7lxt5ijH5w

**Comment by TomGrill** [comment]
Sounds like a bug. Will look into it as soon as i got some free time.

**Comment by TomGrill** [comment]
Sorry I forgot about this. I experience the same problem, however I have not found anything which would explain this. So nothing we can do at the moment.
