### ISSUE TITLE
Need help in ShareDialog

### ISSUE THREAD

**Issue by kranthi521** [TomGrill/gdx-facebook#44]
I am not able to find a way in which I can create a ShareDialog of facebook using this library. Any help in this regard will be highly appreciated.

**Comment by TomGrill** [comment]
ShareDialogs like:
https://developers.facebook.com/docs/sharing/reference/share-dialog or https://developers.facebook.com/docs/sharing/android are not supported by the extension yet. 

So you have two options: Post/Share something to the users feed like it is shown in the https://github.com/TomGrill/gdx-facebook-app or implement the features above to this extension and make a PR. I do not have time to do it my self at the moment.
