### ISSUE TITLE
Maven Project dependency problems

### ISSUE THREAD

**Issue by ysa33** [TomGrill/gdx-facebook#47]
Hello!
We are using libgdx in order to create a game on desktop build with maven.
 For the login we want to use Facebook sign in.
I try to install your project, it went well on gradle but on maven I received this error : 
    "[java] gdx-facebook (1.2.4): Error installing gdx-facebook (1.2.4) for Desktop
     [java] 
     [java] gdx-facebook (1.2.4): Did you add >> compile "de.tomgrill.gdxfacebook:gdx-facebook-desktop:1.2.4" << to your gradle dependencies? View https://github.com/TomGrill/gdx-facebook/wiki for more information."

The SignIn fonction finish by the "onError" function  and with the message "Sign in error. gdx-facebook (1.2.4) is not installed."

But I had gdx-facebook to the pom.xml and the depency was generated well so i don't understand.

Thank you!

**Comment by TomGrill** [comment]
I never used maven but afaik pom.xml and build.gradle just differ in syntax when it comes to dependencies. Looks like you missed something for the desktop sub project. Cannot help here never used maven, sorry.
