### ISSUE TITLE
Regarding access token and sign in 

### ISSUE THREAD

**Issue by kali-gandaki** [TomGrill/gdx-facebook#48]
This library requires that you call sign in everytime app is launched . Only then the access token is loaded or renewed . I think this causes problem in some cases such as mine where i show a login by facebook button to login but hide the button if the user is already logged in . The access token for native apps is managed by sdk and it has validity of 60 days if no call to the server is made . So it makes no sense to call signin everytime app is launched. When user app requires additional permission , he/she can call signin again . I think issignedIn method should check the local token and check if it is valid or not and return accordingly . The silent sign in ( check validity of existing token ) should be a public method as far as i understand .
I can make the changes but I am not sure whether i am thinking correctly . Am I thinking in the right direction or there is something i am missing ? 

Seems closer to this issue 
#38

Thanks

**Comment by TomGrill** [comment]
_I think this causes problem in some cases such as mine where i show a login by facebook button to login but hide the button if the user is already logged in_

What exactly does not work?

_The access token for native apps is managed by sdk and it has validity of 60 days if no call to the server is made_

Is that true for alle SDKs, Android, iOS and Javascript/GWT?

_So it makes no sense to call signin everytime app is launched._

I rather prefer calling a method once at the app's launch to setup the token state. I think you got a point to split signIn() into something like loadTokens() and signIn(). Or put the token loading into the install() method.

_I think issignedIn method should check the local token and check if it is valid or not and return accordingly_

This is a design question. Validating a token requires a graph request. Putting that request in isSignedIn() would force one to block the current thread and wait for the callback. So I decided to assume a player is signed in when the token exists to avoid blocked threads. So if you want to verify the token in isSignedIn() you must change the method and use a callback parameter like a graph request. To avoid having this requests all over the place in the app's code I went for the simpler approach.

_The silent sign in ( check validity of existing token ) should be a public method as far as i understand_

If you need a token verification you can just create a graph request doing that. Having a method like that was the case before FB removed the silentLogin from SDKs. That is why it no longer exists.

**Comment by kali-gandaki** [comment]
What exactly does not work ?
-> In this case if the user if offline , I have no way to show that user has already logged in to my app . Even if the use is not offline I have no way to show that user has logged in before without calling signin again . 

Is that true for alle SDKs, Android, iOS and Javascript/GWT?
->Its only for android and ios sdk . But why pay the price for other backend's different behaviour . I understand this is a tradeoff for cross platform support , But we can change the way token retrieval and verification  is done in android and ios . It does not require graph request 

So it makes no sense to call signin everytime app is launched.
-> You are correct . But signin behaviour is too bulky in my opinion , we should make it fine grained . eg popping up gui login is not under the control of the user . loadTokens() and signin() will be perfect .

**Comment by TomGrill** [comment]
You can store the information whether the user is was/is signed-in in Preferences.

**Comment by kali-gandaki** [comment]
ok Thanks for the information . I need to make some changes to match my requirements .
