### ISSUE TITLE
find a bug in the AndroidGDXFacebook.java that will break the login process

### ISSUE THREAD

**Issue by ygdx** [TomGrill/gdx-facebook#5]
Great work and very helpful project.  But I found this bug when I try out the example at https://github.com/TomGrill/gdx-facebook-app.

In this example, I first login with read permission and it works correctly.  But after that, when I try to login with publish permission, nothing happens.  Testing was done on an Android device with NO Fackbook app installed.  The read permission login was done through web interface.

After a little debugging, I found the issue in AndroidGDXFacebook.java.  A logic error preventing the login() method correctly login publish permission when read permission is granted first.  If you follow the execution of login() when you already have read permission, your AccessToken.getCurrentAccessToken will not be null, therefore line106 if clause will be false and you reach line116.  Since you have read access token, line116 if clause will be true, then you enter the if clause and further down reach line120 "if (arePermissionsGranted(permissions))", but because this time you asking for publish permission which you don't have (you only have read permission), so this if clause will be false. After this false, the login method finished, you don't get the chance to run line159 LoginManager.getInstance().logInWithPublishPermissions(activity, permissions);  Therefore you never get to longin with publish permission.

Please review the code and correct it if this is indeed not correct.  Also make sure the app works when the gdx-facebook updated to later commit.

Thanks for any discussion.

**Comment by TomGrill** [comment]
Thanks for pointing this out ygdx. I made a dirty quickfix to provide functionality. Latest snapshot is uploaded. 

I need test cases to prevent bugs like this in the future. I will add some test frameworks and do proper testing of the classes in the future. A non dirty fix will follow then.

**Comment by ygdx** [comment]
Sure thing!  Keep up the great work.  Your project is great and helped me tremendously.
