### ISSUE TITLE
Up to date with fb graph?

### ISSUE THREAD

**Issue by MrCharli3** [TomGrill/gdx-facebook#52]
Hi,

Wanted to check if you still keep this updated? Some breaking changes from fb-graph at the moment. For example our app stopped being able to load peoples profile pics. 

From Facebook: 

Your App, xxx, currently has access to Graph API v2.4 which will reach the end of its 2-year lifetime on 09 October, 2017. To ensure a smooth transition, please migrate all calls to Graph API v2.5 or higher.

**Comment by TomGrill** [comment]
The extension should work with any graph-version. 

You can change the version in the Facebook Developer settings for your app: https://developers.facebook.com

And then in your app set the graph version in GDXFacebookConfig.

```
config.GRAPH_API_VERSION = "v2.x";
```
