### ISSUE TITLE
Application quits when trying to login on Desktop

### ISSUE THREAD

**Issue by Zarandor** [TomGrill/gdx-facebook#54]
Hi,
I use launch4j to produce an exe file from the desktop version of my app. 
It works with openjdk 1.8. 
When I try to log in to Facebook the app quits suddenly.

I found out which call caused the crash: 
`JXBrowser.login(permissions, config, this);`
in startGUISignIn method

After some digging I think the problem can be the use of javafx in JXBrowser which is not part of openjdk.

Am I right? And can you propose me a workaround for this ?
Thank you.

**Comment by TomGrill** [comment]
Hi, I do not know of any workaround besides using Oracle Java JDK.

**Comment by Zarandor** [comment]
Ok.
Because libgdx doc only mentioned OpenJDK in Bundling a JRE I assumed it was the only one that works for an executable.
So I tried Oracle JDK and it works.
Thank you.
