### ISSUE TITLE
Warnings from Facebook

### ISSUE THREAD

**Issue by vovakons** [TomGrill/gdx-facebook#61]
I received such a warning from facebook:

> At the moment, the MY_APP_NAME application uses outdated versions of 2.7 Graph API: Facebook SDK for iOS v4.15.1.
> 
> As a result, there is a possibility that your application will no longer function if you do not update it to the Facebook SDK for iOS v4.39.0.
> 
> Since you are the administrator of this application, update it to the latest version of the SDK as soon as possible so that you can continue working with it and use the new features.

build.gradle have dependency line `compile "de.tomgrill.gdxfacebook:gdx-facebook-ios:1.5.0"`

In  your README.MD see 

> iOS RoboVM (7+, Facebook iOS SDK 4.15.1)

Any idea how not to get such warnings from Facebook?

**Comment by TomGrill** [comment]
You can stop the warnings buy upgrading the graph version in developer.facebook.com settings of your app. Also update GDXFacebookConfig.GRAPH_API_VERSION

Note sure which graph version iOS SDK 4.15.1 supports.

Cannot upgrade iOS SDK now. Waiting for this PR https://github.com/MobiVM/robovm-robopods/pull/64 to get latest bindings.

**Comment by vovakons** [comment]
Thanks
