### ISSUE TITLE
Cannot get access token for test user

### ISSUE THREAD

**Issue by SuperBadger** [TomGrill/gdx-facebook#7]
Hi Tom,
Thanks very much for this extremely helpful project, it's made my life a lot easier while implementing FB oauth authentication.

There's a slight problem that popped up - I cannot seem to authenticate test users. Facebook Administrator level user logs in fine (tested on desktop and android) and gets an access token. Tester / test user will not - GDXFacebookCallback<GDXFacebookLoginResult> returns with:

public void onError(GDXFacebookError error) {
System.out.println("Facebook auth error: " + error.getErrorMessage() + " / " + error.getErrorCode() + ":" + error.getErrorSubCode() + ", error type: " + error.getErrorType());}

- console printout is: 
Facebook auth error: (#100) You must provide an app access token or a user access token that is an owner or developer of the app / 100:null, error type: OAuthException.

Login is done using the provided GDXFacebook.loginWithReadPermissions() method, permissions requested are email, public_profile, user_friends. Facebook app is in development status.

Is this a bug or expected behavior and I'm doing something wrong? I've read that debug access tokens require a different URL to validate, and also the exact opposite view that it should work just the same - so I'm confused.

Thanks,

SB.

**Comment by TomGrill** [comment]
I am not exactly sure. Did you create testaccounts on the FB developer page or do you test with real FB accounts?

If there is an issue it might take a while till i can fix it.

**Comment by SuperBadger** [comment]
Tested with both test account and real one (on 'tester' privileges) , they give the same behavior.

**Comment by TomGrill** [comment]
Ok I will look into this in about 10 days.

**Comment by SuperBadger** [comment]
Thank you.

**Comment by TomGrill** [comment]
I looked into this and I am not quite sure what the problem might be. I need more information.

1. Can you set your FB app in published mode and try again?
2. Please share your code.

**Comment by SuperBadger** [comment]
1. Yes, I'm almost certain publishing the app on facebook will fix this based on the error message, but I don't want to publish until the development is finished - thus it's in development mode.

2. Here you go (replace APP_ID and call FBMethods.getInstance().loginRead() from anywhere, login window opens, once login details for a Tester-privileged account are put in, returns "Facebook auth error: (#100) You must provide an app access token or a user access token that is an owner or developer of the app / 100:null, error type: OAuthException" ):

public class FBMethods {
    private static FBMethods instance;

    public static FBMethods getInstance() {
        if (instance == null) {
            instance = new FBMethods();
        }
        return instance;
    }

    private FBMethods() {
        GDXFacebookConfig config = new GDXFacebookConfig();
        config.APP_ID = "0123456789123456"; // required
        GDXFacebookSystem.install(config);
    }

    public void loginRead() {
        ArrayList <String> permissions = new ArrayList<String>();
        permissions.add("email");
        permissions.add("public_profile");
        permissions.add("user_friends");
        GDXFacebookSystem.getGDXFacebook().loginWithReadPermissions(permissions, new GDXFacebookCallback<GDXFacebookLoginResult>() {
            @Override
            public void onSuccess(GDXFacebookLoginResult result) {
                System.out.println("logged in Facebook");
                // Login successful
            }

            @Override
            public void onError(GDXFacebookError error) {
                System.out.println("Facebook auth error: " + error.getErrorMessage() + " / " + error.getErrorCode() + ":" + error.getErrorSubCode() + ", error type: " + error.getErrorType());
                System.out.println(getAccessToken());
                // Error handling
            }

            @Override
            public void onFail(Throwable t) {
                // When the login fails
            }

            @Override
            public void onCancel() {
                // When the user cancels the login process
            }
        });
    }

    public String getAccessToken() {
        return GDXFacebookSystem.getGDXFacebook().getAccessToken().getToken();
    }
}

**Comment by TomGrill** [comment]
The DesktopGDXFacebook class makes a call to "debug_token". To make this call you need an app acces token or admin token. Thats why testusers do not work.

The extension got a little bit messy over time and I will have to clean it up and rewrite some stuff to fix this accordingly. This will take a few days I think.

**Comment by TomGrill** [comment]
This issue is now fixed with version 0.6.0
