### ISSUE TITLE
Unable to login when running Desktop app on Mac OS

### ISSUE THREAD

**Issue by asherbar** [TomGrill/gdx-facebook#8]
Reproduced on Yosemite OS 10.10.5.
Steps to reproduce:
1. Run the Desktop application of [gdx-facebook-app](https://github.com/TomGrill/gdx-facebook-app)
2. On the application window, click the "Login to Facebook" button
**Expected result:** A login window should open
**Actual result:** The following message is printed to the log-
> gdx-facebook: Skip installing gdx-facebook for Android. Not running Android. 
> 
> gdx-facebook: Skip installing gdx-facebook for iOS. Not running iOS. 
> 
> gdx-facebook: gdx-facebook for Desktop installed successfully.
2015-09-27 00:29:32.152 java[8639:250770] *** Assertion failure in -[NSMenu itemAtIndex:], /SourceCache/AppKit/AppKit-1348.17/Menus.subproj/NSMenu.m:893
> 2015-09-27 00:29:32.241 java[8639:250770] Invalid parameter not satisfying: (index >= 0) && (index < [_itemArray count])
> 2015-09-27 00:29:32.551 java[8639:250770] (
> 	0   CoreFoundation                      0x00007fff96f6003c __exceptionPreprocess + 172
> 	1   libobjc.A.dylib                     0x00007fff908f676e objc_exception_throw + 43
> 	2   CoreFoundation                      0x00007fff96f5fe1a +[NSException raise:format:arguments:] + 106
> 	3   Foundation                          0x00007fff98b9799b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fff95241e41 -[NSMenu itemAtIndex:] + 164
> 	5   AppKit                              0x00007fff95235a90 -[NSApplication(NSWindowsMenu) setWindowsMenu:] + 218
> 	6   libglass.dylib                      0x00000001178bd7f1 -[GlassApplication runLoop:] + 1585
> 	7   Foundation                          0x00007fff98b61dd0 __NSThreadPerformPerform + 293
> 	8   CoreFoundation                      0x00007fff96e7ca01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
> 	9   CoreFoundation                      0x00007fff96e6eb8d __CFRunLoopDoSources0 + 269
> 	10  CoreFoundation                      0x00007fff96e6e1bf __CFRunLoopRun + 927
> 	11  CoreFoundation                      0x00007fff96e6dbd8 CFRunLoopRunSpecific + 296
> 	12  HIToolbox                           0x00007fff96b1656f RunCurrentEventLoopInMode + 235
> 	13  HIToolbox                           0x00007fff96b162ea ReceiveNextEventCommon + 431
> 	14  HIToolbox                           0x00007fff96b1612b _BlockUntilNextEventMatchingListInModeWithFilter + 71
> 	15  AppKit                              0x00007fff952488ab _DPSNextEvent + 978
> 	16  AppKit                              0x00007fff95247e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
> 	17  libosxapp.dylib                     0x000000010ef82b56 -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 124
> 	18  AppKit                              0x00007fff9523daf3 -[NSApplication run] + 594
> 	19  libosxapp.dylib                     0x000000010ef829b9 +[NSApplicationAWT runAWTLoopWithApp:] + 156
> 	20  liblwawt.dylib                      0x000000010eedca5a -[AWTStarter starter:] + 1591
> 	21  Foundation                          0x00007fff98b61dd0 __NSThreadPerformPerform + 293
> 	22  CoreFoundation                      0x00007fff96e7ca01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
> 	23  CoreFoundation                      0x00007fff96e6eb8d __CFRunLoopDoSources0 + 269
> 	24  CoreFoundation                      0x00007fff96e6e1bf __CFRunLoopRun + 927
> 	25  CoreFoundation                      0x00007fff96e6dbd8 CFRunLoopRunSpecific + 296
> 	26  java                                0x00000001082ba4bc CreateExecutionEnvironment + 871
> 	27  java                                0x00000001082b4cac JLI_Launch + 1952
> 	28  java                                0x00000001082ba819 main + 101
> 	29  java                                0x00000001082b4504 start + 52
> )

and nothing happens, i.e., a Facebook login window does not appear.

**Comment by TomGrill** [comment]
Hi I developed using Linux, never tested Mac Desktop. I will look into this.

**Comment by TomGrill** [comment]
The desktop app works on my mac. I run it with

./gradlew desktop:run

I am not familiar with that crash logs but I might have an idea.
The extension makes uses classes of the javafx package which only comes with Oracle Java. Do you use openjdk?

What java version do you have?

terminal:
java -version

**Comment by asherbar** [comment]
I ran the desktop app from Android Studio. When I run it from terminal with `./gradlew desktop:run` I get an exception:
```
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:run
gdx-facebook: Skip installing gdx-facebook for Android. Not running Android. 

gdx-facebook: Skip installing gdx-facebook for iOS. Not running iOS. 

gdx-facebook: gdx-facebook for Desktop installed successfully.
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at de.tomgrill.gdxfacebook.desktop.DesktopGDXFacebook$2.run(DesktopGDXFacebook.java:78)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 14 more
BUILD SUCCESSFUL
```
I'm unfamiliar with `openjdk` so I reckon I'm not using it. How can I check to be sure?
My java version: 1.7.0_09

**Comment by TomGrill** [comment]
The error says: java.lang.NoClassDefFoundError: javafx/application/Application

Your installed java version is missing javafx. You need to install Oracle Java or install JavaFX

Maybe this link helps: https://docs.oracle.com/javafx/2/installation_2-2/javafx-installation-mac.htm

**Comment by asherbar** [comment]
For others having similar problems, I solved it by downloading and installing the [latest JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html).
