### ISSUE TITLE
"Uncaught ReferenceError: require is not defined" logged when run in Android

### ISSUE THREAD

**Issue by chandujr** [TomGrill/gdx-facebook#9]
As I mentioned in the LibGDX forum, I"m getting this error in my log when I sign in to the Facebook account in Android. (This is before the account grants permission to the app)

`I/chromium﹕ [INFO:CONSOLE(1)] "Uncaught ReferenceError: require is not defined"`

How I implemented the extension:

* Followed your wiki and and added all the necessary code additions in `build.gradle` file.
* Added this to my Game class:

```Java
GDXFacebookConfig fbconfig = new GDXFacebookConfig();
fbconfig.PREF_FILENAME = ".facebookSessionData";
fbconfig.APP_ID = FB_APP_ID;
gdxFacebook = GDXFacebookSystem.install(fbconfig);
```

* And in my Screen class, in a login button listener, I added this:

```Java
List<String> permissions = new ArrayList<String>();
permissions.add("email");
permissions.add("public_profile");
permissions.add("user_friends");

game.gdxFacebook.loginWithReadPermissions(permissions, new GDXFacebookCallback<GDXFacebookLoginResult>() {
    @Override
    public void onSuccess(GDXFacebookLoginResult result) {
        System.out.println("Login: Success--Userid: " + result.getAccessToken().getUserId());
        getUserInfo();
    }

    @Override
    public void onError(GDXFacebookError error) {
        System.out.println("Login: Error - " + error.toString());
    }

    @Override
    public void onFail(Throwable t) {
        System.out.println("Login: Failed");
    }

    @Override
    public void onCancel() {
        System.out.println("Login: Cancelled");
    }
});
```

I'm not getting this callback. Nothing is printed on the log except the uncaught reference error. On googling, I found out that it might be because Facebook SDK is not initialized.

**Comment by chandujr** [comment]
In the login() method of `AndroidGDXFacebook` class, there's this part:

```Java
if (AccessToken.getCurrentAccessToken() == null) {
    accessToken = loadAccessToken();

    if (accessToken != null) {
        AccessToken reuseToken = fromGDXFacebookToken(accessToken);
        AccessToken.setCurrentAccessToken(reuseToken);
    }
}
```
It is quite confusing.

**Comment by TomGrill** [comment]
Could not reproduce the error so far. I found similar errors in combination with javascript. So I assume the error comes from chromium browser. The extension opens the browser to proceed with the FB login. Have you tried it with another device/simulator? What device/android version are you running?

Maybe we can figure it out together on skype (tomgrill) if you are open for a screensession.

**Comment by chandujr** [comment]
Yeah sure, I can come to Skype. Please give me your skype username and I will be right there.

Btw, I tried on both emulator(API 21 - 5.0.1) and device (Yu Yureka [AO5510 - 5.0.2]). I don't have FB app installed on the device. The browser login is what I get when login button is clicked.

**Comment by TomGrill** [comment]
my skypename is: tomgrill

**Comment by chandujr** [comment]
okay

**Comment by TomGrill** [comment]
Solved:

Dont't forget to add `super.onActivityResult(requestCode, resultCode, data);` when you overwrite your `onActivityResult()` method in the AndroidLauncher

**Comment by chandujr** [comment]
Working great! :)
